# Assignment-3:

In [ ]:
#to perform the operations on the numpy we should import numpy
import numpy as np


# question-1:

In [3]:
import numpy as np
arr=np.arange(2,50,3)
print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


# question-2:

In [ ]:
lst1=[]
n1=int(input("enter the list1 length"))
for i in range(n1):
    data1=int(input())
    lst1.append(data1)
lst2=[] 
n2=int(input("enter the list2 length"))
for i in range(n2):
    data2=int(input())
    lst1.append(data2)
    

In [ ]:
import numpy as np
array1=np.array(lst1)
array2=np.array(lst2)
print (array1)
print (array2)
from numpy import concatenate, sort
array3 = concatenate((array1,array2))
array3.sort(kind='mergesort')
print(array3)



# question-3:

In [2]:
import numpy as np
arr = np.array( [[ 1, 2, 3, 4, 5, 6],
                 [ 7, 8, 9, 10, 11, 12]] )
print("Array is of type: ", type(arr))
print("No. of dimensions: ", arr.ndim)
print("Size of array: ", arr.size)


Array is of type:  <class 'numpy.ndarray'>
No. of dimensions:  2
Size of array:  12


# question-4:

In [5]:
import numpy as np
arr1=np.array([1,2,3,4,5,6])
print(arr1)
arr2=np.reshape(arr1,(-1,2))
print(arr2)

[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]]


# question-5:

In [5]:
import numpy as np
arr1=[2,4,6]
print ("Square Value of arr1 : \n", np.square(arr1)) 
arr2=[1,3,5]
print ("Square Value of arr1 : \n", np.square(arr2)) 
f = np.array(arr1)
g = np.array(arr2)
print('Horizontal Append:', np.hstack((f, g)))
print('Vertical Append:', np.vstack((f, g)))


Square Value of arr1 : 
 [ 4 16 36]
Square Value of arr1 : 
 [ 1  9 25]
Horizontal Append: [2 4 6 1 3 5]
Vertical Append: [[2 4 6]
 [1 3 5]]


# question-6:

In [15]:
import numpy as np
lst1=np.array([1,2,3,4,5,6,7,8,9])
(unique,counts)=np.unique(lst1,return_counts=True)
values=np.asarray((unique,counts)).T
print(values)

[[1 1]
 [2 1]
 [3 1]
 [4 1]
 [5 1]
 [6 1]
 [7 1]
 [8 1]
 [9 1]]
